name: publishtodockerhub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t mf244/Dockerfile:latest
      - name: publish
        run: |
          docker push mf244/Dockerfile:latest
